# Generated by Django 4.2.1 on 2023-08-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('rep_date', models.DateTimeField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youareright.board')),
            ],
        ),
    ]
