# Generated by Django 4.2.4 on 2023-08-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('SOCIETY', '사회'), ('CULTURE', '문화'), ('POLITICS', '정치'), ('ECONOMY', '경제'), ('ENTERTAINMENT', '연예'), ('FREE', '자유')], default='', max_length=100),
        ),
    ]
