# Generated by Django 4.2.1 on 2023-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
