# Generated by Django 4.2.4 on 2023-08-16 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hash_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 22, 0, 6, 701209, tzinfo=datetime.timezone.utc)),
        ),
    ]
