# Generated by Django 4.2.1 on 2023-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youareright", "0002_board_file_board_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="hit",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
