# Generated by Django 4.2.4 on 2023-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='youareright.hashtag'),
        ),
    ]
