# Generated by Django 4.2.1 on 2023-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0003_board_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='File',
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(),
        ),
    ]
