# Generated by Django 4.2.1 on 2023-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youareright", "0004_remove_board_file_alter_board_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(verbose_name="data published")),
                ("body", models.TextField()),
                ("user_name", models.CharField(default="", max_length=20)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="reply", name="reply",),
        migrations.DeleteModel(name="Board",),
        migrations.DeleteModel(name="Reply",),
    ]
