# Generated by Django 4.2.4 on 2023-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0004_board_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hashtag_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
