# Generated by Django 4.2.4 on 2023-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0005_board_hashtag_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
