# Generated by Django 4.2.1 on 2023-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youareright", "0005_post_remove_reply_reply_delete_board_delete_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
