# Generated by Django 4.2.4 on 2023-08-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0006_hashtag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='hashtag_field',
        ),
    ]
