# Generated by Django 4.2.4 on 2023-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0007_remove_board_hashtag_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='count',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
