# Generated by Django 4.2.4 on 2023-08-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youareright', '0008_alter_hashtag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hash_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
